name: TjornOS CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/audit-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential llvm clang
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --workspace --verbose
    - name: Run security tests
      run: cargo test --package tjorn-security --verbose
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Run clippy
      run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-latest
    needs: [security-audit, test]
    steps:
    - uses: actions/checkout@v3
    - name: Build release
      run: cargo build --release
    - name: Create bootable image
      run: ./scripts/create_bootable.sh
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tjornos-release
        path: target/x86_64-unknown-none/release/tjornos.iso 